In [1]:
# import CartPole.py from local directory
import CartPole, CartPole1, sf3utility
# import matplotlib.collections
# import matplotlib.pyplot as plt
import numpy as np
# import scipy.interpolate, scipy.stats.qmc
# import random, copy

# plt.rcParams["font.family"] = "Georgia"
# #plt.rcParams['figure.figsize'] = [9.0, 7.0]
# #plt.rcParams['figure.dpi'] = 400

# # store results for later
# cache = {}

In [2]:
%matplotlib notebook

In [3]:
states = np.random.rand( 10,5 ) * 10 - 5

for state in states:

    s5 = sRK4 = state
    
    for x in range(40):
        s5   = CartPole.perform_action5( s5 )
        sRK4 = CartPole.perform_action_RK4( sRK4 )
        
    print( s5 )
    print( sRK4 )

[-133.04609469  -29.52057639   -2.92571801    3.87330965   -3.51632846]
[-133.03707665  -29.62662263   -2.86775968    3.06372994   -3.51632846]
[-79.90392633 -18.34645551  -3.92189998  -6.15577992  -1.91388081]
[-79.84114082 -18.00163722  -4.23552794  -3.80764153  -1.91388081]
[67.8492224  19.36998407  4.8489027  -1.44302427  2.8419336 ]
[67.93572963 18.88342831  4.04774958 -6.46595089  2.8419336 ]
[-54.99868227  -9.27951932   4.65976586  -1.40917602  -0.64294335]
[-55.3108117  -10.42250965   2.98717637  -8.93746703  -0.64294335]
[35.28333283 10.52975672 -2.12487044  0.40708295  1.60469935]
[35.27463486 10.46437547 -2.16685821 -0.55212906  1.60469935]
[131.47198323  31.09834422   4.49208124   7.87983307   3.59921077]
[130.80481036  29.94520177   3.92053891  -9.18853883   3.59921077]
[38.37753418 15.68268845 -2.9820813   4.25005563  2.58913628]
[38.38690629 15.65940721 -2.92440279  4.0940824   2.58913628]
[89.3976553  24.99712771 -3.04007186 -3.6610341   3.57835671]
[89.38876135 25.0300